### ISSUE TITLE
MVIDs reported by ildasm and getnetguids differ

### ISSUE THREAD

**Issue by Rob3rtS** [CylanceSPEAR/GetNETGUIDs#1]
Hi,

ildasm and getnetguids show different MVIDs, e.g.:
ildasm /text "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETCore\v4.5\Microsoft.CSharp.dll" | find MVID
// MVID: {D998552A-3BF9-4639-B04B-4D163CD4C0BC}

python2 getnetguids.py "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETCore\v4.5\Microsoft.CSharp.dll"
None    2a5598d9-f93b-3946-b04b-4d163cd4c0bc    1142649c3394ac58d363ab2653a41291f670524bb11c858d1c6478d4cbbbee32

I tried it on Windows 7 Enterprise SP1 x64 with ActivePython 2.7.2.
ildasm was C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A/bin/NETFX 4.0 Tools/ildasm.exe

One of the two tools seems to have a bug ;-) or there is something mixed up. Can you please take a look, what could be going wrong?

Thanks,
Robert

**Comment by bwall** [comment]
That's very interesting.  I'll take a look.  

From looking at the results posted here, I'm seeing that the first two sections of the MVIDs have swapped endianness but the rest of the sections are unaffected.  I'll look at additional tools to confirm which one has an issue, but it should be an easy fix either way. :)

Currently the parsing of the MVID is very simple in GetNETGUIDs, essentially converting the binary GUID to hex, then splitting it into its sections.

**Comment by ghost** [comment]
Good catch.  Yeah, it looks like the endianness is incorrect in GetNETGUIDs for converting from binary GUID to a text GUID for the first two sections.  I'll fix this shortly.

**Comment by Rob3rtS** [comment]
Effect of fix confirmed! Thank you for your prompt reaction.
